#!/bin/bash

opt=$1
msg=$2
b=$3  #brnach
package=$4 

case $opt in

start_conn)
    adb tcpip 5555
    ;;
conn_device)
    adb connect 192.168.1.109:5555
    ;;
start_main)
    adb shell am start -a android.intent.action.MAIN -n $packages/.SplashActivity
    ;;
uninstall)
    adb uninstall com.example.urbano_park_est
    ;;
install)
    adb install com.example.urbano_park_est
    ;;
start)
    adb shell am start -c android.intent.category.HOME -a android.intent.action.MAIN
    ;;
list_packege)
    adb shell pm  list packages -e
    ;;
monkey)
    adb shell monkey -p $packages -c android.intent.category.LAUNCHER 1
    ;;
reinstalar) 
    adb -s 192.168.1.106:5555 install -r app-debug.apk
    ;;
uninstall_package)
    adb shell pm uninstall $packages
    ;;
esac
